language = "en"

[name]
	align = "left"
	first_name_size = "2.4em"
	last_name_size = "3.8em"
[colour]
	side = "#7EACB5"
	main = "#C96868"
	tag = "#FFE9B1"
[font]
	main = "Bitter"
	title = "Fira Sans"
	tag = "Fira Code"
	size = "10pt"
[margin]
	x = "1.4cm"
	y = "1.4cm"
	column_separator = ".8cm"